name = "Root's Cyber Warfare"
prefix = "root_cyberwarfare"
mainprefix = "z"

[files]
include = [
    "mod.cpp",        
    "meta.cpp",       
    "LICENSE",
    "root_cyberwarfare_logo.paa",
    "README.md",
]
exclude = [
    "repomix-output.xml",
    ".gitignore",
]

[properties]
author = "Root"
url = "https://github.com/A3-Root/Root_Cyberwarfare"

[lints.sqf.banned_commands]
options.banned = [
    "execVM",
]
options.ignore = [
    "addPublicVariableEventHandler",
]